modLoader="javafml"
loaderVersion="[47,)"
license="LGPL V3"

[[mods]]
modId="cantswimupwaterfalls"
version="1.0"
displayName="You Cannot Swim Up Waterfalls"
displayURL="https://www.curseforge.com/minecraft/mc-mods/you-cannot-swim-up-waterfalls"
authors="StephenBarnes, PotionSeeker"
description='''
Prevent swimming upwards in falling water.
'''

[[dependencies.cantswimupwaterfalls]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cantswimupwaterfalls]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"